################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
BoardSupportPackage/src/AsciiLib.obj: ../BoardSupportPackage/src/AsciiLib.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -Ooff --opt_for_speed=0 --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/BoardSupportPackage/DriverLib" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/G8RTOS" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/BoardSupportPackage/inc" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/simplelink/include" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/board" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/cc3100_usage" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/simplelink" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/SL_Common" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/spi_cc3100" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage" --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --advice:power="all" --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="BoardSupportPackage/src/AsciiLib.d_raw" --obj_directory="BoardSupportPackage/src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

BoardSupportPackage/src/BSP.obj: ../BoardSupportPackage/src/BSP.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -Ooff --opt_for_speed=0 --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/BoardSupportPackage/DriverLib" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/G8RTOS" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/BoardSupportPackage/inc" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/simplelink/include" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/board" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/cc3100_usage" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/simplelink" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/SL_Common" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/spi_cc3100" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage" --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --advice:power="all" --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="BoardSupportPackage/src/BSP.d_raw" --obj_directory="BoardSupportPackage/src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

BoardSupportPackage/src/BackChannelUart.obj: ../BoardSupportPackage/src/BackChannelUart.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -Ooff --opt_for_speed=0 --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/BoardSupportPackage/DriverLib" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/G8RTOS" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/BoardSupportPackage/inc" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/simplelink/include" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/board" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/cc3100_usage" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/simplelink" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/SL_Common" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/spi_cc3100" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage" --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --advice:power="all" --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="BoardSupportPackage/src/BackChannelUart.d_raw" --obj_directory="BoardSupportPackage/src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

BoardSupportPackage/src/ClockSys.obj: ../BoardSupportPackage/src/ClockSys.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -Ooff --opt_for_speed=0 --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/BoardSupportPackage/DriverLib" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/G8RTOS" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/BoardSupportPackage/inc" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/simplelink/include" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/board" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/cc3100_usage" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/simplelink" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/SL_Common" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/spi_cc3100" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage" --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --advice:power="all" --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="BoardSupportPackage/src/ClockSys.d_raw" --obj_directory="BoardSupportPackage/src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

BoardSupportPackage/src/Joystick.obj: ../BoardSupportPackage/src/Joystick.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -Ooff --opt_for_speed=0 --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/BoardSupportPackage/DriverLib" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/G8RTOS" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/BoardSupportPackage/inc" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/simplelink/include" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/board" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/cc3100_usage" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/simplelink" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/SL_Common" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/spi_cc3100" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage" --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --advice:power="all" --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="BoardSupportPackage/src/Joystick.d_raw" --obj_directory="BoardSupportPackage/src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

BoardSupportPackage/src/LCDlib.obj: ../BoardSupportPackage/src/LCDlib.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -Ooff --opt_for_speed=0 --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/BoardSupportPackage/DriverLib" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/G8RTOS" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/BoardSupportPackage/inc" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/simplelink/include" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/board" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/cc3100_usage" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/simplelink" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/SL_Common" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/spi_cc3100" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage" --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --advice:power="all" --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="BoardSupportPackage/src/LCDlib.d_raw" --obj_directory="BoardSupportPackage/src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

BoardSupportPackage/src/RGBLeds.obj: ../BoardSupportPackage/src/RGBLeds.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -Ooff --opt_for_speed=0 --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/BoardSupportPackage/DriverLib" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/G8RTOS" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/BoardSupportPackage/inc" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/simplelink/include" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/board" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/cc3100_usage" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/simplelink" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/SL_Common" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/spi_cc3100" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage" --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --advice:power="all" --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="BoardSupportPackage/src/RGBLeds.d_raw" --obj_directory="BoardSupportPackage/src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

BoardSupportPackage/src/bme280.obj: ../BoardSupportPackage/src/bme280.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -Ooff --opt_for_speed=0 --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/BoardSupportPackage/DriverLib" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/G8RTOS" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/BoardSupportPackage/inc" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/simplelink/include" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/board" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/cc3100_usage" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/simplelink" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/SL_Common" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/spi_cc3100" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage" --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --advice:power="all" --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="BoardSupportPackage/src/bme280.d_raw" --obj_directory="BoardSupportPackage/src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

BoardSupportPackage/src/bme280_support.obj: ../BoardSupportPackage/src/bme280_support.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -Ooff --opt_for_speed=0 --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/BoardSupportPackage/DriverLib" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/G8RTOS" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/BoardSupportPackage/inc" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/simplelink/include" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/board" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/cc3100_usage" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/simplelink" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/SL_Common" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/spi_cc3100" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage" --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --advice:power="all" --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="BoardSupportPackage/src/bme280_support.d_raw" --obj_directory="BoardSupportPackage/src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

BoardSupportPackage/src/bmi160.obj: ../BoardSupportPackage/src/bmi160.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -Ooff --opt_for_speed=0 --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/BoardSupportPackage/DriverLib" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/G8RTOS" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/BoardSupportPackage/inc" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/simplelink/include" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/board" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/cc3100_usage" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/simplelink" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/SL_Common" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/spi_cc3100" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage" --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --advice:power="all" --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="BoardSupportPackage/src/bmi160.d_raw" --obj_directory="BoardSupportPackage/src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

BoardSupportPackage/src/bmi160_support.obj: ../BoardSupportPackage/src/bmi160_support.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -Ooff --opt_for_speed=0 --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/BoardSupportPackage/DriverLib" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/G8RTOS" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/BoardSupportPackage/inc" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/simplelink/include" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/board" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/cc3100_usage" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/simplelink" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/SL_Common" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/spi_cc3100" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage" --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --advice:power="all" --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="BoardSupportPackage/src/bmi160_support.d_raw" --obj_directory="BoardSupportPackage/src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

BoardSupportPackage/src/demo_sysctl.obj: ../BoardSupportPackage/src/demo_sysctl.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -Ooff --opt_for_speed=0 --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/BoardSupportPackage/DriverLib" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/G8RTOS" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/BoardSupportPackage/inc" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/simplelink/include" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/board" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/cc3100_usage" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/simplelink" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/SL_Common" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/spi_cc3100" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage" --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --advice:power="all" --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="BoardSupportPackage/src/demo_sysctl.d_raw" --obj_directory="BoardSupportPackage/src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

BoardSupportPackage/src/i2c_driver.obj: ../BoardSupportPackage/src/i2c_driver.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -Ooff --opt_for_speed=0 --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/BoardSupportPackage/DriverLib" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/G8RTOS" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/BoardSupportPackage/inc" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/simplelink/include" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/board" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/cc3100_usage" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/simplelink" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/SL_Common" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/spi_cc3100" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage" --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --advice:power="all" --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="BoardSupportPackage/src/i2c_driver.d_raw" --obj_directory="BoardSupportPackage/src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

BoardSupportPackage/src/opt3001.obj: ../BoardSupportPackage/src/opt3001.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -Ooff --opt_for_speed=0 --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/BoardSupportPackage/DriverLib" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/G8RTOS" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/BoardSupportPackage/inc" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/simplelink/include" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/board" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/cc3100_usage" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/simplelink" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/SL_Common" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/spi_cc3100" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage" --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --advice:power="all" --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="BoardSupportPackage/src/opt3001.d_raw" --obj_directory="BoardSupportPackage/src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

BoardSupportPackage/src/tmp007.obj: ../BoardSupportPackage/src/tmp007.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -Ooff --opt_for_speed=0 --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/BoardSupportPackage/DriverLib" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/G8RTOS" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/BoardSupportPackage/inc" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/simplelink/include" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/board" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/cc3100_usage" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/simplelink" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/SL_Common" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage/spi_cc3100" --include_path="C:/Users/dean4ta/OneDrive - University of Florida/Documents/Fall 2018 UF/uP II/code/Lab5MicroP2/CC3100SupportPackage" --include_path="C:/ti/ccsv8/ccs_base/arm/include" --include_path="C:/ti/ccsv8/ccs_base/arm/include/CMSIS" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.2.LTS/include" --advice:power="all" --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="BoardSupportPackage/src/tmp007.d_raw" --obj_directory="BoardSupportPackage/src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '


